### ISSUE TITLE
change base directory

### ISSUE THREAD

**Issue by DeeeeLAN** [sebastiencs/sidebar.el#13]
Is there an easy way to specify a new starting directory? Navigating to my project is a pain, but if I had a command I could use to type in the base directory, that would be easy.

**Comment by m-ar-c** [comment]
Indeed, it would be nice to be able to select a base dir, with C-u M-x sidebar-open for example. Or a special command after sidebar is opened. But the way things are also make sense : one sidebar per frame, once you have a frame and a sidebar you work on a project and you're glad that 'M-x sidebar-open' (or whatever keybinding you set up) just open the base dir of your project. If you want to work on another project in the same time you just make another frame and set up another sidebar base directory I think.

**Comment by DeeeeLAN** [comment]
Yeah that makes sense, and honestly it has been so long, I don't even remember the original reason I was frustrated and filed an issue here.
