### ISSUE TITLE
[Feature Request] Better navigation in xterm-mouse-mode

### ISSUE THREAD

**Issue by bstut** [sebastiencs/sidebar.el#2]
Features like a selectable line to change the current directory to its parent or being able to open a file by clicking on it

**Comment by sebastiencs** [comment]
@bstut You can already open a file by clicking on it with `xterm-mouse-mode`. It doesn't work for you ?

**Comment by sebastiencs** [comment]
@bstut You can now click on the header line change the current directory :)

**Comment by sebastiencs** [comment]
@bstut I'm closing the issue, feel free to reopen it
