### ISSUE TITLE
[Feature request] Toggle visibility of hidden files

### ISSUE THREAD

**Issue by Unisay** [sebastiencs/sidebar.el#3]
By pressing `h` I can toggle visibility of the hidden buffers, but same key doesn't work for files.

**Comment by sebastiencs** [comment]
There should be all files already listed, which files aren't ?

**Comment by Unisay** [comment]
I am afraid I don't understand your question. Let me clarify what I meant:
- user presses 'h' - hidden files disappear from list.
- user presses 'h' again - hidden files appear in the list.

**Comment by sebastiencs** [comment]
I see, I'm leaving on holliday for 2 weeks, I will implement that when I'm back :)

**Comment by sebastiencs** [comment]
@Unisay Done !
